version: '3.1'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - '6379:6379'
    environment:
      - REDIS_PORT=6379
    volumes:
      - ./docker/redis/data:/data
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - './docker/mongodb/data:/data/db'
    ports:
      - '27017:27017'
      - '27018:27018'
      - '27019:27019'
      - '8081:8081'
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node16
    ports:
      - '3000:3000'
    volumes:
      - './:/src'
    links:
      - mongo:mongodb
      - redis:redis
    restart: always
